/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrewRouteImport } from './routes/crew'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as DrainsRouteImport } from './routes/drains'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as VerificationLabRouteImport } from './routes/verification-lab'
import { Route as ApiWeatherRouteImport } from './routes/api/weather'
import { Route as CitizenReportRouteImport } from './routes/citizen.report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewRoute = CrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const DrainsRoute = DrainsRouteImport.update({
  id: '/drains',
  path: '/drains',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationLabRoute = VerificationLabRouteImport.update({
  id: '/verification-lab',
  path: '/verification-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeatherRoute = ApiWeatherRouteImport.update({
  id: '/api/weather',
  path: '/api/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenReportRoute = CitizenReportRouteImport.update({
  id: '/citizen/report',
  path: '/citizen/report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crew': typeof CrewRoute
  '/dashboard': typeof DashboardRoute
  '/dispatch': typeof DispatchRoute
  '/drains': typeof DrainsRoute
  '/impact': typeof ImpactRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/verification-lab': typeof VerificationLabRoute
  '/api/weather': typeof ApiWeatherRoute
  '/citizen/report': typeof CitizenReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crew': typeof CrewRoute
  '/dashboard': typeof DashboardRoute
  '/dispatch': typeof DispatchRoute
  '/drains': typeof DrainsRoute
  '/impact': typeof ImpactRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/verification-lab': typeof VerificationLabRoute
  '/api/weather': typeof ApiWeatherRoute
  '/citizen/report': typeof CitizenReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crew': typeof CrewRoute
  '/dashboard': typeof DashboardRoute
  '/dispatch': typeof DispatchRoute
  '/drains': typeof DrainsRoute
  '/impact': typeof ImpactRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/verification-lab': typeof VerificationLabRoute
  '/api/weather': typeof ApiWeatherRoute
  '/citizen/report': typeof CitizenReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crew'
    | '/dashboard'
    | '/dispatch'
    | '/drains'
    | '/impact'
    | '/login'
    | '/map'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/verification-lab'
    | '/api/weather'
    | '/citizen/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crew'
    | '/dashboard'
    | '/dispatch'
    | '/drains'
    | '/impact'
    | '/login'
    | '/map'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/verification-lab'
    | '/api/weather'
    | '/citizen/report'
  id:
    | '__root__'
    | '/'
    | '/crew'
    | '/dashboard'
    | '/dispatch'
    | '/drains'
    | '/impact'
    | '/login'
    | '/map'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/verification-lab'
    | '/api/weather'
    | '/citizen/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrewRoute: typeof CrewRoute
  DashboardRoute: typeof DashboardRoute
  DispatchRoute: typeof DispatchRoute
  DrainsRoute: typeof DrainsRoute
  ImpactRoute: typeof ImpactRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  VerificationLabRoute: typeof VerificationLabRoute
  ApiWeatherRoute: typeof ApiWeatherRoute
  CitizenReportRoute: typeof CitizenReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew': {
      id: '/crew'
      path: '/crew'
      fullPath: '/crew'
      preLoaderRoute: typeof CrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drains': {
      id: '/drains'
      path: '/drains'
      fullPath: '/drains'
      preLoaderRoute: typeof DrainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification-lab': {
      id: '/verification-lab'
      path: '/verification-lab'
      fullPath: '/verification-lab'
      preLoaderRoute: typeof VerificationLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weather': {
      id: '/api/weather'
      path: '/api/weather'
      fullPath: '/api/weather'
      preLoaderRoute: typeof ApiWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/report': {
      id: '/citizen/report'
      path: '/citizen/report'
      fullPath: '/citizen/report'
      preLoaderRoute: typeof CitizenReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrewRoute: CrewRoute,
  DashboardRoute: DashboardRoute,
  DispatchRoute: DispatchRoute,
  DrainsRoute: DrainsRoute,
  ImpactRoute: ImpactRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  VerificationLabRoute: VerificationLabRoute,
  ApiWeatherRoute: ApiWeatherRoute,
  CitizenReportRoute: CitizenReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
